export const SEARCH_ITEM_ON = "SEARCH_ITEM_ON";
export const SEARCH_ITEM_OFF = "SEARCH_ITEM_OFF";
export const CLEAR_SEARCH_ITEM = "CLEAR_SEARCH_ITEM";
export const EXPAND_ITEM_ON = "EXPAND_ITEM_ON";
export const EXPAND_ITEM_OFF = "EXPAND_ITEM_OFF";